---
Name: markdown
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - LoveDuckie\SilverStripe\Markdown\Extensions\MarkdownFieldExtension
SilverStripe\ORM\DataObject:
  extensions:
    - LoveDuckie\SilverStripe\Markdown\Extensions\MarkdownDataObjectExtension
